name: sample-monorepo

static_sites:
- name: frontend
  environment_slug: html
  github:
    repo: techswarn/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: frontend
  index_document: hello.html
  error_document: error.html
  routes:
  - path: /frontend

- name: landing
  github:
    repo: techswarn/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: landing
  dockerfile_path: landing/Dockerfile
  output_dir: /app
  error_document: error.html
  routes:
  - path: /landing

services:
- name: api
  environment_slug: go
  github:
    repo: techswarn/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: api
  routes:
  - path: /api