name: sample-monorepo
region: blr
services:
- environment_slug: go
  github:
    branch: main
    deploy_on_push: true
    repo: techswarn/sample-monorepo
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: api
  routes:
  - path: /api
  source_dir: api
static_sites:
- environment_slug: html
  error_document: error.html
  github:
    branch: main
    deploy_on_push: true
    repo: techswarn/sample-monorepo
  index_document: hello.html
  name: frontend
  routes:
  - path: /frontend
  source_dir: frontend
- dockerfile_path: landing/Dockerfile
  error_document: error.html
  github:
    branch: main
    deploy_on_push: true
    repo: techswarn/sample-monorepo
  name: landing
  output_dir: /app
  routes:
  - path: /landing
  source_dir: landing