alerts:
- rule: DEPLOYMENT_FAILED
- rule: DEPLOYMENT_LIVE
name: myapp
region: blr
  services:
  - name: api
    environment_slug: go
    git:
      branch: main
      repo_clone_url: https://github.com/digitalocean/sample-monorepo.git
    source_dir: api
    routes:
    - path: /api
  - name: landing
    git:
      branch: main
      repo_clone_url: https://github.com/digitalocean/sample-monorepo.git
    source_dir: landing
    dockerfile_path: landing/Dockerfile
    output_dir: /app
    error_document: error.html
    routes:
    - path: /landing